create extension if not exists pgcrypto;

create type public.organisation_role as enum ('owner','admin','member','viewer');
create type public.property_status as enum ('active','inactive','archived');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organisations (id uuid primary key default gen_random_uuid(), name text not null check (length(name) between 1 and 120), slug text not null unique, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organisation_members (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.organisation_role not null default 'viewer', created_at timestamptz not null default now(), unique(organisation_id,user_id));
create index organisation_members_user_idx on public.organisation_members(user_id);

create table public.properties (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, display_name text not null, address_line_1 text not null, address_line_2 text, town_or_city text not null, county text, postcode text not null, ownership_entity_name text, property_type text, status public.property_status not null default 'active', notes text, drive_folder_id text, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, check ((status = 'archived') = (archived_at is not null)));
create index properties_org_status_idx on public.properties(organisation_id,status);
create table public.document_categories (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, name text not null, slug text not null, sort_order integer not null default 0, is_system boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organisation_id,slug));
create table public.documents (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, category_id uuid references public.document_categories(id) on delete set null, title text not null, original_filename text not null, standardised_filename text, document_date date, description text, drive_file_id text, drive_web_url text, mime_type text, size_bytes bigint check (size_bytes is null or size_bytes >= 0), uploaded_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);
create index documents_org_property_idx on public.documents(organisation_id,property_id);
create table public.timeline_events (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, document_id uuid references public.documents(id) on delete set null, event_type text not null check (event_type in ('property_created','property_updated','property_archived','document_added','document_updated','note_added')), title text not null, description text, event_date timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index timeline_org_property_date_idx on public.timeline_events(organisation_id,property_id,event_date desc);
create table public.google_drive_connections (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, connected_by uuid not null references auth.users(id), google_account_email text not null, root_folder_id text, status text not null check (status in ('connected','disconnected','error')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), disconnected_at timestamptz);

create function public.is_org_member(org_id uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.organisation_members where organisation_id=org_id and user_id=auth.uid()) $$;
create function public.has_org_role(org_id uuid, allowed public.organisation_role[]) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.organisation_members where organisation_id=org_id and user_id=auth.uid() and role=any(allowed)) $$;
revoke all on function public.is_org_member(uuid) from public; grant execute on function public.is_org_member(uuid) to authenticated;
revoke all on function public.has_org_role(uuid,public.organisation_role[]) from public; grant execute on function public.has_org_role(uuid,public.organisation_role[]) to authenticated;

alter table public.profiles enable row level security; alter table public.organisations enable row level security; alter table public.organisation_members enable row level security; alter table public.properties enable row level security; alter table public.document_categories enable row level security; alter table public.documents enable row level security; alter table public.timeline_events enable row level security; alter table public.google_drive_connections enable row level security;
create policy profiles_select on public.profiles for select using (id=auth.uid() or exists(select 1 from public.organisation_members mine join public.organisation_members theirs using(organisation_id) where mine.user_id=auth.uid() and theirs.user_id=profiles.id));
create policy profiles_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());
create policy organisations_select on public.organisations for select using (public.is_org_member(id));
create policy organisations_update on public.organisations for update using (public.has_org_role(id,array['owner','admin']::public.organisation_role[])) with check (public.has_org_role(id,array['owner','admin']::public.organisation_role[]));
create policy members_select on public.organisation_members for select using (public.is_org_member(organisation_id));
create policy members_insert on public.organisation_members for insert with check (public.has_org_role(organisation_id,array['owner','admin']::public.organisation_role[]) and role not in ('owner'));
create policy members_update on public.organisation_members for update using (public.has_org_role(organisation_id,array['owner']::public.organisation_role[]) and user_id<>auth.uid()) with check (public.has_org_role(organisation_id,array['owner']::public.organisation_role[]) and user_id<>auth.uid());
create policy members_delete on public.organisation_members for delete using (public.has_org_role(organisation_id,array['owner']::public.organisation_role[]) and user_id<>auth.uid());
create policy properties_select on public.properties for select using (public.is_org_member(organisation_id));
create policy properties_insert on public.properties for insert with check (created_by=auth.uid() and public.has_org_role(organisation_id,array['owner','admin','member']::public.organisation_role[]));
create policy properties_update on public.properties for update using (public.has_org_role(organisation_id,array['owner','admin','member']::public.organisation_role[])) with check (public.has_org_role(organisation_id,array['owner','admin','member']::public.organisation_role[]));
create policy categories_select on public.document_categories for select using (public.is_org_member(organisation_id));
create policy categories_write on public.document_categories for all using (public.has_org_role(organisation_id,array['owner','admin']::public.organisation_role[])) with check (public.has_org_role(organisation_id,array['owner','admin']::public.organisation_role[]));
create policy documents_select on public.documents for select using (public.is_org_member(organisation_id));
create policy documents_write on public.documents for all using (public.has_org_role(organisation_id,array['owner','admin','member']::public.organisation_role[])) with check (public.has_org_role(organisation_id,array['owner','admin','member']::public.organisation_role[]) and uploaded_by=auth.uid());
create policy timeline_select on public.timeline_events for select using (public.is_org_member(organisation_id));
create policy timeline_insert on public.timeline_events for insert with check (created_by=auth.uid() and public.has_org_role(organisation_id,array['owner','admin','member']::public.organisation_role[]));
create policy drive_select on public.google_drive_connections for select using (public.is_org_member(organisation_id));
create policy drive_write on public.google_drive_connections for all using (public.has_org_role(organisation_id,array['owner','admin']::public.organisation_role[])) with check (public.has_org_role(organisation_id,array['owner','admin']::public.organisation_role[]) and connected_by=auth.uid());

create function public.seed_default_categories(org_id uuid) returns void language sql security definer set search_path='' as $$ insert into public.document_categories(organisation_id,name,slug,sort_order,is_system) values (org_id,'Tenancy','tenancy',1,true),(org_id,'Compliance','compliance',2,true),(org_id,'Finance','finance',3,true),(org_id,'Maintenance','maintenance',4,true),(org_id,'Correspondence','correspondence',5,true),(org_id,'Photos','photos',6,true) on conflict(organisation_id,slug) do nothing $$;
revoke all on function public.seed_default_categories(uuid) from public, anon, authenticated;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ declare org_id uuid; org_name text; begin insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing; org_name:=coalesce(nullif(new.raw_user_meta_data->>'organisation_name',''),split_part(new.email,'@',1)||'''s organisation'); insert into public.organisations(name,slug,created_by) values(org_name,lower(regexp_replace(org_name,'[^a-zA-Z0-9]+','-','g'))||'-'||substr(new.id::text,1,8),new.id) on conflict(slug) do update set name=excluded.name returning id into org_id; insert into public.organisation_members(organisation_id,user_id,role) values(org_id,new.id,'owner') on conflict(organisation_id,user_id) do nothing; perform public.seed_default_categories(org_id); return new; end $$;
revoke all on function public.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create function public.create_property_with_event(input jsonb) returns uuid language plpgsql security invoker set search_path='' as $$ declare org_id uuid; property_id uuid; begin select organisation_id into org_id from public.organisation_members where user_id=auth.uid() order by created_at limit 1; if org_id is null then raise exception 'No organisation membership'; end if; insert into public.properties(organisation_id,display_name,address_line_1,address_line_2,town_or_city,county,postcode,ownership_entity_name,property_type,notes,created_by) values(org_id,input->>'displayName',input->>'addressLine1',nullif(input->>'addressLine2',''),input->>'townOrCity',nullif(input->>'county',''),input->>'postcode',nullif(input->>'ownershipEntityName',''),nullif(input->>'propertyType',''),nullif(input->>'notes',''),auth.uid()) returning id into property_id; insert into public.timeline_events(organisation_id,property_id,event_type,title,created_by) values(org_id,property_id,'property_created','Property created',auth.uid()); return property_id; end $$;
create function public.update_property_with_event(target_property_id uuid,input jsonb) returns void language plpgsql security invoker set search_path='' as $$ declare changed integer; begin update public.properties set display_name=input->>'displayName',address_line_1=input->>'addressLine1',address_line_2=nullif(input->>'addressLine2',''),town_or_city=input->>'townOrCity',county=nullif(input->>'county',''),postcode=input->>'postcode',ownership_entity_name=nullif(input->>'ownershipEntityName',''),property_type=nullif(input->>'propertyType',''),notes=nullif(input->>'notes',''),updated_at=now() where id=target_property_id and (display_name,address_line_1,coalesce(address_line_2,''),town_or_city,coalesce(county,''),postcode,coalesce(ownership_entity_name,''),coalesce(property_type,''),coalesce(notes,'')) is distinct from (input->>'displayName',input->>'addressLine1',input->>'addressLine2',input->>'townOrCity',input->>'county',input->>'postcode',input->>'ownershipEntityName',input->>'propertyType',input->>'notes'); get diagnostics changed=row_count; if changed>0 then insert into public.timeline_events(organisation_id,property_id,event_type,title,created_by) select organisation_id,id,'property_updated','Property details updated',auth.uid() from public.properties where id=target_property_id; end if; end $$;
create function public.archive_property_with_event(target_property_id uuid) returns void language plpgsql security invoker set search_path='' as $$ begin update public.properties set status='archived',archived_at=now(),updated_at=now() where id=target_property_id and status<>'archived'; if found then insert into public.timeline_events(organisation_id,property_id,event_type,title,created_by) select organisation_id,id,'property_archived','Property archived',auth.uid() from public.properties where id=target_property_id; end if; end $$;
revoke all on function public.create_property_with_event(jsonb),public.update_property_with_event(uuid,jsonb),public.archive_property_with_event(uuid) from public, anon;
grant execute on function public.create_property_with_event(jsonb),public.update_property_with_event(uuid,jsonb),public.archive_property_with_event(uuid) to authenticated;
